/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace SharedStructs {
  export type CollectionInfoStruct = {
    collection: PromiseOrValue<string>;
    maxSupply: PromiseOrValue<BigNumberish>;
    minted: PromiseOrValue<BigNumberish>;
    xSize: PromiseOrValue<BigNumberish>;
    ySize: PromiseOrValue<BigNumberish>;
  };

  export type CollectionInfoStructOutput = [
    string,
    number,
    number,
    number,
    number
  ] & {
    collection: string;
    maxSupply: number;
    minted: number;
    xSize: number;
    ySize: number;
  };
}

export interface IMashInterface extends utils.Interface {
  functions: {
    "getCollection(uint256)": FunctionFragment;
    "getLayerNames(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getCollection" | "getLayerNames"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getCollection",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLayerNames",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLayerNames",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IMash extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMashInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getCollection(
      _collectionNr: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[SharedStructs.CollectionInfoStructOutput]>;

    getLayerNames(
      collectionNr: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;
  };

  getCollection(
    _collectionNr: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<SharedStructs.CollectionInfoStructOutput>;

  getLayerNames(
    collectionNr: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  callStatic: {
    getCollection(
      _collectionNr: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<SharedStructs.CollectionInfoStructOutput>;

    getLayerNames(
      collectionNr: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;
  };

  filters: {};

  estimateGas: {
    getCollection(
      _collectionNr: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLayerNames(
      collectionNr: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getCollection(
      _collectionNr: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLayerNames(
      collectionNr: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
