/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IRender, IRenderInterface } from "../../Mash.sol/IRender";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "collection",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "layerId",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "traitId",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "pfpRender",
            type: "bool",
          },
          {
            internalType: "uint8",
            name: "scale",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "xOffset",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "yOffset",
            type: "uint8",
          },
        ],
        internalType: "struct SharedStructs.LayerStruct[7]",
        name: "layerIds",
        type: "tuple[7]",
      },
    ],
    name: "previewCollage",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint8",
            name: "collection",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "layerId",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "traitId",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "pfpRender",
            type: "bool",
          },
          {
            internalType: "uint8",
            name: "scale",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "xOffset",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "yOffset",
            type: "uint8",
          },
        ],
        internalType: "struct SharedStructs.LayerStruct[7]",
        name: "layerIds",
        type: "tuple[7]",
      },
      {
        components: [
          {
            internalType: "address",
            name: "collection",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "maxSupply",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "minted",
            type: "uint16",
          },
          {
            internalType: "uint8",
            name: "xSize",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "ySize",
            type: "uint8",
          },
        ],
        internalType: "struct SharedStructs.CollectionInfo[7]",
        name: "_collections",
        type: "tuple[7]",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRender__factory {
  static readonly abi = _abi;
  static createInterface(): IRenderInterface {
    return new utils.Interface(_abi) as IRenderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRender {
    return new Contract(address, _abi, signerOrProvider) as IRender;
  }
}
