/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mashSol from "./Mash.sol";
export type { mashSol };
import type * as renderSol from "./Render.sol";
export type { renderSol };
export * as factories from "./factories";
export type { IRender } from "./Mash.sol/IRender";
export { IRender__factory } from "./factories/Mash.sol/IRender__factory";
export type { Mash } from "./Mash.sol/Mash";
export { Mash__factory } from "./factories/Mash.sol/Mash__factory";
export type { IMash } from "./Render.sol/IMash";
export { IMash__factory } from "./factories/Render.sol/IMash__factory";
export type { Render } from "./Render.sol/Render";
export { Render__factory } from "./factories/Render.sol/Render__factory";
